---

- name: Download kubeconfig file for cluster id {{ rke_cluster_id }}
  uri:
    url: "{{ rancher_api_url }}/v3/clusters/{{ rke_cluster_id }}?action=generateKubeconfig"
    method: POST
    validate_certs: false
    return_content: true
    headers:
      Authorization: "Bearer {{ rancher_token }}"
  register: kubeconfig_data
  no_log: True

- name: Make kubeconfig storage directory root
  file:
    path: "{{ kubeconfig_dir_root }}"
    mode: '0750'
    state: directory

- name: Make kubeconfig storage directory
  file:
    path: "{{ kubeconfig_dir }}"
    mode: '0750'
    state: directory

- name: Store cluster kubeconfig in storage directory
  copy:
    content: "{{ kubeconfig_data.json.config }}"
    dest: "{{ kubeconfig_dir }}/kubeconfig_{{ rke_cluster_id }}"
    mode: "0700"
  no_log: True
