--- 

# Install external secrets
#---------------------------------------------------------
- name: "Install external secrets helm chart on cluster: {{ rke_cluster_id }}"
  shell: |
    helm repo add external-secrets "{{ external_secrets_repo }}"
    helm upgrade --install --version "{{ external_secrets_version }}" -n external-secrets --create-namespace external-secrets external-secrets/external-secrets
  environment:
    KUBECONFIG: "{{ kubeconfig_dir }}/kubeconfig_{{ rke_cluster_id }}"
#---------------------------------------------------------