---
- name: Create temporary build directory
  tempfile:
    state: directory
    suffix: build
  register: tempdir

- name: Get kubectl hash
  uri:
    url:  "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl.sha256"
    return_content: true
  register: kubectl_checksum

- name: Download kubectl
  get_url:
    url:  "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: 0755
    owner: root
    group: root
    checksum: "sha256:{{ kubectl_checksum.content }}"

- name: Download Helm
  get_url:
    url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "{{ tempdir.path }}"
    checksum: "sha256:https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz.sha256sum"

- name: Unarchive helm tarball
  unarchive:
    src: "{{ tempdir.path }}/helm-v{{ helm_version}}-linux-amd64.tar.gz"
    dest: "{{ tempdir.path }}"

- name: Install helm
  copy:
    force: false
    src: "{{ tempdir.path }}/linux-amd64/helm"
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root

- name: Use the registered var and the file module to remove the temporary file
  ansible.builtin.file:
    path: "{{ tempdir.path }}"
    state: absent
  when: tempdir.path is defined
